### ISSUE TITLE
Ember Mirage and DRF adapter are incompatible for acceptance tests

### ISSUE THREAD

**Issue by gone** [dustinfarris/ember-django-adapter#100]
When attempting to run acceptance tests, pretender will bail out rather than making a request.  Possibly related to #33

**Comment by dustinfarris** [comment]
Interesting.  I wonder what part of EDA is conflicting with Ember Mirage.  Is there a sample app anywhere I can look at?

**Comment by dustinfarris** [comment]
Can you give us any output or anything else to help us diagnose the issue here?

**Comment by gone** [comment]
Yeah I'll throw together a demo and post it

**Comment by dustinfarris** [comment]
@gone Is this still a problem for you?

**Comment by dustinfarris** [comment]
Closing.  Please feel free to reopen if this continues to be a problem.

**Comment by aaronlelevier** [comment]
I had a similar error. 

In one project, I had `ember-cli-mirage` and `ember-django-adapter` working together and the other it didn't.

Here is the stack trace from my error:

```
MirageError {description: "Mirage: undefined", fileName: undefined, lineNumber: undefined, message: "Mirage: Your Ember app tried to GET 'api/summaries…ig.js file. Did you forget to add your namespace?", name: "Error", …}
description: "Mirage: undefined"
fileName: undefined
lineNumber: undefined
message: "Mirage: Your Ember app tried to GET 'api/summaries/?page=1',↵         but there was no route defined to handle this request.↵         Define a route that matches this path in your↵         mirage/config.js file. Did you forget to add your namespace?"
name: "Error"
number: undefined
stack: "Mirage: Error: Your Ember app tried to GET 'api/summaries/?page=1',↵         but there was no route defined to handle this request.↵         Define a route that matches this path in your↵         mirage/config.js file. Did you forget to add your namespace?↵    at new MirageError (http://localhost:7357/assets/vendor.js:136095:21)↵    at assert (http://localhost:7357/assets/vendor.js:136082:13)↵    at Pretender.unhandledRequest (http://localhost:7357/assets/vendor.js:140927:29)↵    at Pretender.handleRequest (http://localhost:7357/assets/vendor.js:65147:14)↵    at FakeRequest.send (http://localhost:7357/assets/vendor.js:64916:21)↵    at Object.send (http://localhost:7357/assets/vendor.js:9941:10)↵    at Function.ajax (http://localhost:7357/assets/vendor.js:9547:15)↵    at Class._ajaxRequest (http://localhost:7357/assets/vendor.js:220184:15)↵    at http://localhost:7357/assets/vendor.js:220174:17↵    at initializePromise (http://localhost:7357/assets/vendor.js:61620:7)"
__proto__: Error
```

Upon inspecting the difference between the projects, I had imported the add-on differently in `app/adapters/application.js`. 

One had:

```javascript
// app/adapters/application.js
import DRFAdapter from './drf';

export default DRFAdapter.extend({
    namespace: 'api',
});
```

The other had:

```javascript
// app/adapters/application.js
import DRFAdapter from 'ember-django-adapter/adapters/drf';

export default DRFAdapter.extend({
    namespace: 'api',
});
```

The latter with the full path import worked and fixed the above `ember-cli-mirage` error.
