### ISSUE TITLE
Fastboot - Error: The adapter operation was aborted

### ISSUE THREAD

**Issue by gandalfar** [dustinfarris/ember-django-adapter#171]
Anyone got ember-django-adapter working with Fastboot? When I'm trying it with a simple app (just one model and ember-django-adapter), I get the following stacktrace:

```
DEBUG: -------------------------------
DEBUG: Ember                : 2.10.2
DEBUG: Ember Data           : 2.10.0
DEBUG: Ember Django Adapter : 1.1.3
DEBUG: -------------------------------
Ember FastBoot running at http://[::]:3000
Error while processing route: posts The adapter operation was aborted Error: The adapter operation was aborted
    at Error.AdapterError (/Users/gandalf/build/guides/dist/fastboot/vendor.js:83959:16)
    at ErrorClass (/Users/gandalf/build/guides/dist/fastboot/vendor.js:83985:24)
    at ajaxError (/Users/gandalf/build/guides/dist/fastboot/vendor.js:85735:15)
    at Object.hash.error (/Users/gandalf/build/guides/dist/fastboot/vendor.js:85312:23)
    at fire (/Users/gandalf/build/guides/node_modules/jquery-deferred/lib/jquery-callbacks.js:78:30)
    at Object.fireWith (/Users/gandalf/build/guides/node_modules/jquery-deferred/lib/jquery-callbacks.js:188:7)
    at Object.fire [as reject] (/Users/gandalf/build/guides/node_modules/jquery-deferred/lib/jquery-callbacks.js:195:10)
    at onError (/Users/gandalf/build/guides/node_modules/najax/lib/najax.js:206:9)
    at dataHandler (/Users/gandalf/build/guides/node_modules/najax/lib/najax.js:141:18)
    at IncomingMessage.<anonymous> (/Users/gandalf/build/guides/node_modules/najax/lib/najax.js:194:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
2016-12-25T21:03:22.101Z 500 Unknown Error: Error: The adapter operation was aborted
    at Error.AdapterError (/Users/gandalf/build/guides/dist/fastboot/vendor.js:83959:16)
    at ErrorClass (/Users/gandalf/build/guides/dist/fastboot/vendor.js:83985:24)
    at ajaxError (/Users/gandalf/build/guides/dist/fastboot/vendor.js:85735:15)
    at Object.hash.error (/Users/gandalf/build/guides/dist/fastboot/vendor.js:85312:23)
    at fire (/Users/gandalf/build/guides/node_modules/jquery-deferred/lib/jquery-callbacks.js:78:30)
    at Object.fireWith (/Users/gandalf/build/guides/node_modules/jquery-deferred/lib/jquery-callbacks.js:188:7)
    at Object.fire [as reject] (/Users/gandalf/build/guides/node_modules/jquery-deferred/lib/jquery-callbacks.js:195:10)
    at onError (/Users/gandalf/build/guides/node_modules/najax/lib/najax.js:206:9)
    at dataHandler (/Users/gandalf/build/guides/node_modules/najax/lib/najax.js:141:18)
    at IncomingMessage.<anonymous> (/Users/gandalf/build/guides/node_modules/najax/lib/najax.js:194:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

`routes/posts.js`
```
import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    return this.store.query('post', {'slug': 'foobar'});
  }

});
```

**Comment by gandalfar** [comment]
I forgot to mention that Fastboot still works, it would just probably be better if it didn't emit error.

**Comment by dustinfarris** [comment]
@gandalfar thanks for reporting, will look into this.

**Comment by gandalfar** [comment]
No more errors with 2.0.0 for me. Thanks for maintaining this adapter!
