### ISSUE TITLE
Dev mode fails, prod mode works.

### ISSUE THREAD

**Issue by ewilson** [dustinfarris/ember-django-adapter#46]
This is what I see in the console when dev mode fails with the adapter. When I run as:

    $ ember serve --environment production

It seems to work fine. I'll use that as my dev mode for now.

You can look at my code at https://github.com/ewilson/titlematch_web

Error while processing route: tournaments.index Could not find module ember-django-adapter/adapters/drf Error: Could not find module ember-django-adapter/adapters/drf
    at requireModule (http://localhost:4200/assets/vendor.js:65:13)
    at reify (http://localhost:4200/assets/vendor.js:48:30)
    at requireModule (http://localhost:4200/assets/vendor.js:76:17)
    at resolveOther (http://localhost:4200/assets/vendor.js:63103:20)
    at apply (http://localhost:4200/assets/vendor.js:32885:27)
    at superWrapper (http://localhost:4200/assets/vendor.js:32457:15)
    at __exports__.default.EmberObject.extend.resolve (http://localhost:4200/assets/vendor.js:16818:27)
    at Object.resolve [as resolver] (http://localhost:4200/assets/vendor.js:16432:25)
    at resolve (http://localhost:4200/assets/vendor.js:14968:32)
    at Object.Container.resolve (http://localhost:4200/assets/vendor.js:14548:16)ember.js:15373 logToConsoleember.js:26312 logErrorember.js:26269 defaultActionHandlers.errorember.js:26360 triggerEventember.js:46873 triggerember.js:46718 Transition.triggerember.js:46523 (anonymous function)ember.js:47307 tryCatchember.js:47319 invokeCallbackember.js:47290 publishember.js:47232 publishRejectionember.js:29435 (anonymous function)ember.js:679 DeferredActionQueues.invokeember.js:749 DeferredActionQueues.flushember.js:135 Backburner.endember.js:190 Backburner.runember.js:18223 runember.js:2542 runInitializejquery.js:3143 firejquery.js:3255 self.fireWithjquery.js:3467 jQuery.extend.readyjquery.js:3498 completed

**Comment by holandes22** [comment]
I saw something similar when I tried to add ic-autocomplete to the Brocfile. It was failing on the drf adapter just as a coincidence for being the first. Try remove the ember-data includes and see what happens (not sure you need it anyway as ember-cli knows to minify the asset for production)

**Comment by ewilson** [comment]
OK, removed the following (assuming that's what you meant) and it works now.

    app.import({
        development: 'vendor/ember-data/ember-data.js',
        production:  'vendor/ember-data/ember-data.prod.js'
    }, {
        'ember-data': [
            'default'
        ]
    });

Please let me know if that isn't what you meant to do (if I've removed too much.)

**Comment by holandes22** [comment]
Yes, that was exactly what I meant. Glad to hear it's working

**Comment by dustinfarris** [comment]
@ewilson can we close this?
